Change GEOSGeom to GEOSGeometry and GEOSCoordSeq to GEOSCoordSequence
The C types GEOSGeom and GEOSCoordSeq are themselves pointer types.
The underlying struct typedefs are called GEOSGeometry and
GEOSCoordSequence.

This fixes C compilation errors with future compilers:

      src/_geoslib.c:6918:28: error: passing argument 1 of ‘GEOSCoordSeq_setY’ from incompatible pointer type
       6918 |   (void)(GEOSCoordSeq_setY(__pyx_v_cs, 0, __pyx_v_dy));
            |                            ^~~~~~~~~~
            |                            |
            |                            GEOSCoordSequence ** {aka struct GEOSCoordSeq_t **}
      /usr/include/geos_c.h:2194:58: note: expected ‘GEOSCoordSequence *’ {aka ‘struct GEOSCoordSeq_t *’} but argument is of type ‘GEOSCoordSequence **’ {aka ‘struct GEOSCoordSeq_t **’}
       2194 | extern int GEOS_DLL GEOSCoordSeq_setY(GEOSCoordSequence* s,
            |                                       ~~~~~~~~~~~~~~~~~~~^