Call the Python version of import_array()
The new approach follows this example:

  <https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html#adding-types>

The C version is a macro with control flow that Cython does not know
anything about.  It introduces a C type error.

This fixes a build failure with some compilers:

      src/_geoslib.c: In function ‘__pyx_pymod_exec__geoslib’:
      src/_geoslib.c:8755:3: error: returning ‘void *’ from a function with return type ‘int’ makes integer from pointer without a cast
       8755 |   import_array();
            |   ^~~~~~~~~~~~