Fix type error in initGEOS() call
The function pointers passed to initGEOS() did not have the correct
type.  A proper fix needs <stdarg.h> support in Cython, which is
currently missing.

This fixes a build failure with Clang 16 and GCC 14.

      src/_geoslib.c: In function ‘__pyx_pymod_exec__geoslib’:
      src/_geoslib.c:8803:12: error: passing argument 1 of ‘initGEOS’ from incompatible pointer type
       8803 |   initGEOS(__pyx_f_8_geoslib_notice_h, __pyx_f_8_geoslib_error_h);
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
            |            |
            |            void (*)(char *, char *)
      In file included from src/_geoslib.c:1219:
      /usr/include/geos_c.h:2074:24: note: expected ‘GEOSMessageHandler’ {aka ‘void (*)(const char *, ...)’} but argument is of type ‘void (*)(char *, char *)’
       2074 |     GEOSMessageHandler notice_function,
            |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      src/_geoslib.c:8803:40: error: passing argument 2 of ‘initGEOS’ from incompatible pointer type
       8803 |   initGEOS(__pyx_f_8_geoslib_notice_h, __pyx_f_8_geoslib_error_h);
            |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
            |                                        |
            |                                        void (*)(char *, char *)
      /usr/include/geos_c.h:2075:24: note: expected ‘GEOSMessageHandler’ {aka ‘void (*)(const char *, ...)’} but argument is of type ‘void (*)(char *, char *)’
       2075 |     GEOSMessageHandler error_function);
            |     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~